pref( "extensions.tbdialout.proto", "callto:" );
pref( "extensions.tbdialout.prefix", "" );
pref( "extensions.tbdialout.plus", "" );
pref( "extensions.tbdialout.tbbuttonadded", false );
pref( "extensions.tbdialout.customurl", "" );
pref( "extensions.tbdialout.customuser", "" );
pref( "extensions.tbdialout.custominbackground", true );
pref( "extensions.tbdialout.loglevel", 2);
pref( "extensions.tbdialout.passmigrated", false );
pref( "extensions.tbdialout.updateshown", "" );
pref( "extensions.tbdialout.showupdatenotes", true);
pref( "extensions.tbdialout.ami.channel", "" );
pref( "extensions.tbdialout.ami.context", "default" );
pref( "extensions.tbdialout.ami.host", "" );
pref( "extensions.tbdialout.ami.port", 5038 );
pref( "extensions.tbdialout.ami.user", "" );
pref( "extensions.tbdialout.ami.callerid", "" );
pref( "extensions.tbdialout.ami.timeout", 15000 );